server:
  port: 8082
spring:
  application:
    name: document-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: Mohammad
    password: myjava123

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create-drop


eureka:

  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9001/eureka}

